KS-3-5 mdrn app chess, added server str parser
UncleKur/KotlinSprint pull request #15
Opened 2024-06-08 09:39 UTC by UncleKur

2024-06-08 20:29 UTC, ievetrovdev requested changes

2024-06-08 20:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val getFromField: String = getMoveInformation.substringBefore('-')
Давай упростим это все. Воспользуйся split. Он может принимать все нужные разделители строки сразу. Затем оперируй полученным массивом строк для решения задачи.

2024-06-08 20:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    var fromField: String = "E2"
Откуда Е2, что это за числа дальше. В задаче же не требуется ничего такого.

2024-06-08 23:43 UTC, UncleKur commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val getFromField: String = getMoveInformation.substringBefore('-')
В таком ключе, решение выходит за рамки урока. Про списки мы же ничего не знаем -_-

2024-06-10 20:13 UTC, ievetrovdev approved these changes
Все верно! Молодец! Иногда полезно отходить от установленных правил, если это помогает лучше выполнить задачу. С каждым новым уроком таких случаев будет меньше, но главное — найти наилучшее решение. Не ограничивайте себя только тем, что уже изучили, но и не используйте то, что вам совсем непонятно.

2024-06-11 13:04 UTC, merged