KS-4-2 crtd Average load inform
UncleKur/KotlinSprint pull request #17
Opened 2024-06-08 18:39 UTC by UncleKur

2024-06-10 12:53 UTC, ievetrovdev requested changes

2024-06-10 12:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +    var categoryInformation = "Груз с весом $load кг и объемом $volume соответствует категории 'Average': ${(load > MIN_WEIGHT && load <= MAX_WEIGHT) && volume < VOLUME_UP_TO}"
Да, код корректный. Но давай чуть улучшим.
Строки слишком длинные (>120 символов), глазу труднее в них ориентироваться. Часто в компаниях вводят правила форматирования, а также специальные утилиты, которые следят за соблюдением правил.

2024-06-11 13:12 UTC, UncleKur commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +    var categoryInformation = "Груз с весом $load кг и объемом $volume соответствует категории 'Average':" +
в идеале я бы это условие занёс в переменную isAverage, которую потом бы переопределял. Но в задаче сказано, что нужно выполнять проверку непосредственно внутри println()

2024-06-12 05:25 UTC, ievetrovdev approved these changes

2024-06-12 09:39 UTC, merged