KS-2-4 crtd buffed inform
UncleKur/KotlinSprint pull request #9
Opened 2024-06-07 10:02 UTC by UncleKur

2024-06-07 15:01 UTC, ievetrovdev requested changes

2024-06-07 15:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val minedCrystalOre = 7f
Все верно, кроме одного момента: переменные `minedCrystalOre `и `minedIronOre `должны быть объявлены как целые числа (Int), а не числа с плавающей точкой (Float). Это позволит избежать лишних преобразований типов и упростит код.

2024-06-07 15:43 UTC, UncleKur commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val minedCrystalOre = 7f
Float я указывал - что бы оно мне считало, а если Int оставить, в консоль вылетает по нулям. Как быть?

2024-06-07 21:29 UTC, ievetrovdev requested changes

2024-06-07 21:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buffedCrystalOre = minedCrystalOre / DEFAULT_PERCENT * POWER_BAFF_PERCENT
Вынеси расчет бонуса отдельно. val bonus = POWER_BAFF_PERCENT / DEFAULT_PERCENT

2024-06-07 21:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buffedIronOre = minedIronOre / DEFAULT_PERCENT * POWER_BAFF_PERCENT
Сделай приведение к целому. val buffedIronOre = (minedIronOre * bonus).toInt()

2024-06-07 21:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val POWER_BAFF_PERCENT = 20
Представь как дробное 20.0
Переименуй, это не константа.

2024-06-07 21:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val DEFAULT_PERCENT = 100
Вынеси в константы из main

2024-06-08 20:23 UTC, ievetrovdev approved these changes
Отличное решение!

2024-06-08 22:58 UTC, merged